# Generated by Django 3.2.8 on 2021-10-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('descreption', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places='2', max_digits=1000)),
                ('summary', models.TextField()),
            ],
        ),
    ]
