# Generated by Django 3.2.8 on 2021-10-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20211013_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='FULFILLED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REQ_NO', models.CharField(max_length=1000, null=True)),
                ('Descreption', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('my_file', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TASKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descreption', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('canceled', 'canceled')], max_length=200, null=True)),
                ('REQ_NO', models.CharField(max_length=1000, null=True)),
                ('my_file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='finaldesscion',
            name='Chiefs',
        ),
        migrations.RemoveField(
            model_name='finaldesscion',
            name='GMANAGER',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='Chiefs',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='GMANAGER',
        ),
        migrations.RemoveField(
            model_name='resent',
            name='Chiefs',
        ),
        migrations.RemoveField(
            model_name='resent',
            name='GMANAGER',
        ),
        migrations.RenameModel(
            old_name='GMANAGER',
            new_name='STAFF',
        ),
        migrations.RenameModel(
            old_name='Chiefs',
            new_name='Whse_Mangament',
        ),
        migrations.DeleteModel(
            name='Accepted',
        ),
        migrations.DeleteModel(
            name='Finaldesscion',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='Resent',
        ),
        migrations.AddField(
            model_name='tasks',
            name='STAFF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.staff'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='Whse_Mangament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.whse_mangament'),
        ),
        migrations.AddField(
            model_name='fulfilled',
            name='STAFF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.staff'),
        ),
        migrations.AddField(
            model_name='fulfilled',
            name='Whse_Mangament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.whse_mangament'),
        ),
    ]
