# Generated by Django 3.2.8 on 2021-10-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211013_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulfilled',
            old_name='REQ_NO',
            new_name='TASK_NO',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='REQ_NO',
            new_name='TASK_NO',
        ),
    ]
