# Generated by Django 3.2.8 on 2021-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211013_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfilled',
            name='my_file',
        ),
        migrations.AlterField(
            model_name='fulfilled',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('didnot finish', 'didnot dinish')], max_length=200, null=True),
        ),
    ]
