# Generated by Django 3.2.8 on 2021-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211013_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfilled',
            name='note',
            field=models.CharField(max_length=1000, null='default'),
        ),
    ]
