# Generated by Django 3.2.8 on 2021-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_fulfilled_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfilled',
            name='note',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
